[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn app:server --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 180 --keep-alive 5"
